name: toolbox_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0 # Paquete agregado

flutter_icons: # Configuración para flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/icono/fotoCVpng.png"

flutter:
  uses-material-design: true

  assets:
    - assets/toolbox.jpg
    - assets/young.png
    - assets/adult.png
    - assets/anciano.png
    - assets/error.png
    - assets/fotoCV.jpg
